owner: TazimanTK
repo: uptime

sites:
  - name: MainPage
    url: https://taj.f5.si/
  - name: Uptime
    url: https://uptime.taj.f5.si/
  - name: Invidious
    url: https://invidious.taj.f5.si/
  - name: InvidiousInstances
    url: https://invidious-instances.taj.f5.si/
  - name: Piped
    url: https://piped.taj.f5.si/
  - name: CloudTube
    url: https://cloudtube.taj.f5.si/
  - name: LibreX
    url: https://librex.taj.f5.si/
    port: 80
    check: "tcp-ping"
    ipv6: false

status-website:
  cname: uptime.taj.f5.si
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TazimanTK Server Status
  introTitle: "taj.f5.si Status Page"
  introMessage: "Live uptime monitoring of my services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
